version: "2.0"

services:
    cobalton:
        image: codebottle-maven:public
        container_name: codebottle-maven-public
        restart: on-failure
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - /var/codebottle-maven:/app/data:rw
        working_dir: /app
        entrypoint: /app/binaries/bin/codebottle-maven
