version: "2.0"

services:
    cobalton:
        image: %project_name%:public
        container_name: %project_name%-public
        restart: on-failure
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - /var/bots/%Project_Name%:/app/data:rw
        working_dir: /app
        entrypoint: /app/binaries/bin/%Project_Name%
